services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
      - N8N_AUTH_EXCLUDE_ENDPOINTS=healthz
      - N8N_PROXY_AUTH_ENABLED=true
      - N8N_PROXY_AUTH_HEADER=X-Authentik-Email
    volumes:
      - ../config/volumes/n8n/data:/home/node/.n8n
    networks:
      - proxy

networks:
  proxy:
    external: true