services:
  n8n:
    image: ghcr.io/n8n-io/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
      - N8N_AUTH_EXCLUDE_ENDPOINTS=healthz
      - N8N_PROXY_AUTH_ENABLED=true
      - N8N_PROXY_AUTH_HEADER=X-Authentik-Email
      - N8N_HOST=n8n.develium.dev
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://n8n.develium.dev
      - N8N_DEFAULT_CORS=TRUE
      - N8N_CORS_ALLOW_ORIGIN=https://n8n.develium.dev
      - WEBHOOK_URL=https://n8n.develium.dev/
    volumes:
      - ../config/volumes/n8n/data:/home/node/.n8n
    networks:
      - proxy

networks:
  proxy:
    external: true