services:
  broker:
    image: docker.io/library/redis:8
    container_name: paperless-broker
    restart: unless-stopped
    volumes:
      - ../config/volumes/paperless/redis:/data
    networks:
      - proxy

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - ../config/volumes/paperless/data:/usr/src/paperless/data
      - ../config/volumes/paperless/media:/usr/src/paperless/media
      - ../config/volumes/paperless/export:/usr/src/paperless/export
      - ../config/volumes/paperless/consume:/usr/src/paperless/consume
    env_file:
      - ../config/env/paperless/.env
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
    networks:
      - proxy

networks:
  proxy:
    external: true
