services:
  wetty:
    image: wettyoss/wetty:latest
    container_name: wetty
    hostname: wetty.develium.dev
    restart: unless-stopped
    environment:
      - SSHHOST=wetty-ssh
      - SSHPORT=22
      - NODE_ENV=production
    volumes:
      - ../config/volumes/wetty:/home/term
    networks:
      - proxy

  wetty-ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: wetty-ssh
    hostname: wetty-ssh
    restart: unless-stopped
    env_file:
      - ../config/env/wetty/.env
    volumes:
      - ../config/volumes/wetty/ssh:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
