services:
  wetty:
    image: wettyoss/wetty:latest
    container_name: wetty
    hostname: wetty.develium.dev
    restart: unless-stopped
    env_file:
      - ../config/env/wetty/.env
    volumes:
      - ../config/volumes/wetty:/home/term
    networks:
      - proxy

networks:
  proxy:
    external: true
